# Generated by Django 6.1 on 2026-09-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('url_codigo', models.URLField(unique=True)),
                ('url_demo', models.URLField(unique=True)),
                ('icono', models.CharField(default='fa-server', max_length=50)),
                ('tecnologias', models.ManyToManyField(blank=True, to='proyectosApp.tecnologia')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
