# Generated by Django 6.1 on 2026-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosApp', '0002_alter_proyecto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
