# Generated by Django 6.1 on 2026-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosApp', '0003_alter_proyecto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url_codigo',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='url_demo',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
