# Generated by Django 6.1 on 2026-09-05 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Fichero PDF del currículum. Al subir uno nuevo se sustituye el anterior.', upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
            },
        ),
    ]
